//go:build !ignore_autogenerated

/*
Copyright 2026 SlashNephy.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRule) DeepCopyInto(out *AccessRule) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(NamedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(UserReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(NamedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRule.
func (in *AccessRule) DeepCopy() *AccessRule {
	if in == nil {
		return nil
	}
	out := new(AccessRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessSpec) DeepCopyInto(out *AccessSpec) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(AccessMode)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]AccessRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	if in.Prune != nil {
		in, out := &in.Prune, &out.Prune
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessSpec.
func (in *AccessSpec) DeepCopy() *AccessSpec {
	if in == nil {
		return nil
	}
	out := new(AccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikApplication) DeepCopyInto(out *AuthentikApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikApplication.
func (in *AuthentikApplication) DeepCopy() *AuthentikApplication {
	if in == nil {
		return nil
	}
	out := new(AuthentikApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthentikApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikApplicationList) DeepCopyInto(out *AuthentikApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthentikApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikApplicationList.
func (in *AuthentikApplicationList) DeepCopy() *AuthentikApplicationList {
	if in == nil {
		return nil
	}
	out := new(AuthentikApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthentikApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikApplicationSpec) DeepCopyInto(out *AuthentikApplicationSpec) {
	*out = *in
	if in.LaunchURL != nil {
		in, out := &in.LaunchURL, &out.LaunchURL
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Publisher != nil {
		in, out := &in.Publisher, &out.Publisher
		*out = new(string)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.OpenInNewTab != nil {
		in, out := &in.OpenInNewTab, &out.OpenInNewTab
		*out = new(bool)
		**out = **in
	}
	if in.HideFromApplicationDashboard != nil {
		in, out := &in.HideFromApplicationDashboard, &out.HideFromApplicationDashboard
		*out = new(bool)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
	if in.Adopt != nil {
		in, out := &in.Adopt, &out.Adopt
		*out = new(AdoptionPolicy)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(ProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Access.DeepCopyInto(&out.Access)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikApplicationSpec.
func (in *AuthentikApplicationSpec) DeepCopy() *AuthentikApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthentikApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikApplicationStatus) DeepCopyInto(out *AuthentikApplicationStatus) {
	*out = *in
	if in.ProviderPK != nil {
		in, out := &in.ProviderPK, &out.ProviderPK
		*out = new(int64)
		**out = **in
	}
	if in.BindingUUIDs != nil {
		in, out := &in.BindingUUIDs, &out.BindingUUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdoptionDiff != nil {
		in, out := &in.AdoptionDiff, &out.AdoptionDiff
		*out = make([]FieldDiff, len(*in))
		copy(*out, *in)
	}
	if in.UnmanagedBindings != nil {
		in, out := &in.UnmanagedBindings, &out.UnmanagedBindings
		*out = make([]UnmanagedBinding, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikApplicationStatus.
func (in *AuthentikApplicationStatus) DeepCopy() *AuthentikApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(AuthentikApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthSpec) DeepCopyInto(out *BasicAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthSpec.
func (in *BasicAuthSpec) DeepCopy() *BasicAuthSpec {
	if in == nil {
		return nil
	}
	out := new(BasicAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldDiff) DeepCopyInto(out *FieldDiff) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldDiff.
func (in *FieldDiff) DeepCopy() *FieldDiff {
	if in == nil {
		return nil
	}
	out := new(FieldDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowReference) DeepCopyInto(out *FlowReference) {
	*out = *in
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowReference.
func (in *FlowReference) DeepCopy() *FlowReference {
	if in == nil {
		return nil
	}
	out := new(FlowReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardAuthDomainSpec) DeepCopyInto(out *ForwardAuthDomainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardAuthDomainSpec.
func (in *ForwardAuthDomainSpec) DeepCopy() *ForwardAuthDomainSpec {
	if in == nil {
		return nil
	}
	out := new(ForwardAuthDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardAuthSingleSpec) DeepCopyInto(out *ForwardAuthSingleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardAuthSingleSpec.
func (in *ForwardAuthSingleSpec) DeepCopy() *ForwardAuthSingleSpec {
	if in == nil {
		return nil
	}
	out := new(ForwardAuthSingleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedReference) DeepCopyInto(out *NamedReference) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedReference.
func (in *NamedReference) DeepCopy() *NamedReference {
	if in == nil {
		return nil
	}
	out := new(NamedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2CredentialsSecretReference) DeepCopyInto(out *OAuth2CredentialsSecretReference) {
	*out = *in
	if in.ClientIDKey != nil {
		in, out := &in.ClientIDKey, &out.ClientIDKey
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretKey != nil {
		in, out := &in.ClientSecretKey, &out.ClientSecretKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2CredentialsSecretReference.
func (in *OAuth2CredentialsSecretReference) DeepCopy() *OAuth2CredentialsSecretReference {
	if in == nil {
		return nil
	}
	out := new(OAuth2CredentialsSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2CredentialsSpec) DeepCopyInto(out *OAuth2CredentialsSpec) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2CredentialsSpec.
func (in *OAuth2CredentialsSpec) DeepCopy() *OAuth2CredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(OAuth2CredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ProviderSpec) DeepCopyInto(out *OAuth2ProviderSpec) {
	*out = *in
	if in.ClientType != nil {
		in, out := &in.ClientType, &out.ClientType
		*out = new(ClientType)
		**out = **in
	}
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]RedirectURI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]ScopeMappingReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SigningKey != nil {
		in, out := &in.SigningKey, &out.SigningKey
		*out = new(NamedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(NamedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]GrantType, len(*in))
		copy(*out, *in)
	}
	if in.SubjectMode != nil {
		in, out := &in.SubjectMode, &out.SubjectMode
		*out = new(SubjectMode)
		**out = **in
	}
	if in.IssuerMode != nil {
		in, out := &in.IssuerMode, &out.IssuerMode
		*out = new(IssuerMode)
		**out = **in
	}
	if in.IncludeClaimsInIDToken != nil {
		in, out := &in.IncludeClaimsInIDToken, &out.IncludeClaimsInIDToken
		*out = new(bool)
		**out = **in
	}
	if in.AccessCodeValidity != nil {
		in, out := &in.AccessCodeValidity, &out.AccessCodeValidity
		*out = new(string)
		**out = **in
	}
	if in.AccessTokenValidity != nil {
		in, out := &in.AccessTokenValidity, &out.AccessTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenValidity != nil {
		in, out := &in.RefreshTokenValidity, &out.RefreshTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenThreshold != nil {
		in, out := &in.RefreshTokenThreshold, &out.RefreshTokenThreshold
		*out = new(string)
		**out = **in
	}
	if in.LogoutURI != nil {
		in, out := &in.LogoutURI, &out.LogoutURI
		*out = new(string)
		**out = **in
	}
	if in.LogoutMethod != nil {
		in, out := &in.LogoutMethod, &out.LogoutMethod
		*out = new(LogoutMethod)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(OAuth2CredentialsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ProviderSpec.
func (in *OAuth2ProviderSpec) DeepCopy() *OAuth2ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OAuth2ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderFlows) DeepCopyInto(out *ProviderFlows) {
	*out = *in
	in.Authorization.DeepCopyInto(&out.Authorization)
	in.Invalidation.DeepCopyInto(&out.Invalidation)
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(FlowReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderFlows.
func (in *ProviderFlows) DeepCopy() *ProviderFlows {
	if in == nil {
		return nil
	}
	out := new(ProviderFlows)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.Flows.DeepCopyInto(&out.Flows)
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(OAuth2ProviderSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyModeSpec) DeepCopyInto(out *ProxyModeSpec) {
	*out = *in
	if in.InternalHostSSLValidation != nil {
		in, out := &in.InternalHostSSLValidation, &out.InternalHostSSLValidation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyModeSpec.
func (in *ProxyModeSpec) DeepCopy() *ProxyModeSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyProviderSpec) DeepCopyInto(out *ProxyProviderSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyModeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ForwardAuthSingle != nil {
		in, out := &in.ForwardAuthSingle, &out.ForwardAuthSingle
		*out = new(ForwardAuthSingleSpec)
		**out = **in
	}
	if in.ForwardAuthDomain != nil {
		in, out := &in.ForwardAuthDomain, &out.ForwardAuthDomain
		*out = new(ForwardAuthDomainSpec)
		**out = **in
	}
	if in.UnauthenticatedPaths != nil {
		in, out := &in.UnauthenticatedPaths, &out.UnauthenticatedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthSpec)
		**out = **in
	}
	if in.InterceptHeaderAuth != nil {
		in, out := &in.InterceptHeaderAuth, &out.InterceptHeaderAuth
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenValidity != nil {
		in, out := &in.AccessTokenValidity, &out.AccessTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenValidity != nil {
		in, out := &in.RefreshTokenValidity, &out.RefreshTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(NamedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Outpost != nil {
		in, out := &in.Outpost, &out.Outpost
		*out = new(NamedReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyProviderSpec.
func (in *ProxyProviderSpec) DeepCopy() *ProxyProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectURI) DeepCopyInto(out *RedirectURI) {
	*out = *in
	if in.MatchingMode != nil {
		in, out := &in.MatchingMode, &out.MatchingMode
		*out = new(MatchingMode)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(RedirectURIType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectURI.
func (in *RedirectURI) DeepCopy() *RedirectURI {
	if in == nil {
		return nil
	}
	out := new(RedirectURI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeMappingReference) DeepCopyInto(out *ScopeMappingReference) {
	*out = *in
	if in.ScopeName != nil {
		in, out := &in.ScopeName, &out.ScopeName
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeMappingReference.
func (in *ScopeMappingReference) DeepCopy() *ScopeMappingReference {
	if in == nil {
		return nil
	}
	out := new(ScopeMappingReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnmanagedBinding) DeepCopyInto(out *UnmanagedBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnmanagedBinding.
func (in *UnmanagedBinding) DeepCopy() *UnmanagedBinding {
	if in == nil {
		return nil
	}
	out := new(UnmanagedBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserReference) DeepCopyInto(out *UserReference) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.PK != nil {
		in, out := &in.PK, &out.PK
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserReference.
func (in *UserReference) DeepCopy() *UserReference {
	if in == nil {
		return nil
	}
	out := new(UserReference)
	in.DeepCopyInto(out)
	return out
}
